### ISSUE TITLE
Undefined variable in get_pixels

### ISSUE THREAD

**Issue by brianpmarks** [trinketapp/sensehat-examples#1]
@waywaaard, let me know if there is a better place for an issue like this...

When I try the [eyes.py example](https://github.com/trinketapp/sensehat-examples/blob/master/led/eyes.py) in trinket, I get this error: `NameError: name 'y' is not defined on line 307 in src/lib/sense_hat.py` 

https://github.com/trinketapp/skulpt/blob/sense_hat/src/lib/sense_hat.py#L307

**Comment by brianpmarks** [comment]
Same error with the [rotation.py example](https://github.com/trinketapp/sensehat-examples/blob/master/led/rotation.py).

**Comment by ebertmi** [comment]
Fixed in https://github.com/trinketapp/skulpt/commit/f53ba3484c058f08499e9ff822a2fd8f2d10da7e

**Comment by brianpmarks** [comment]
Looks good! 🎆
